services:
  tests:
    extends:
      file: docker-compose.build.yml
      service: dev
    command: npm x -- node-builder test --suite=integration --watch
    env_file:
      - env.d/integration-test
    volumes:
      - ${BUILDKITE_BUILD_CHECKOUT_PATH:-.}:/workdir
      - /workdir/node_modules

secrets:
  npmrc:
    file: ${NPMRC_FILE}
