services:
  dev:
    image: ${SERVE_DOCKER_REGISTRY}/meandu/pci-dss-page-tampering/dev:${DOCKER_TAG}
    build:
      target: dev
      secrets:
        - npmrc

  service:
    image: ${SERVE_DOCKER_REGISTRY}/meandu/pci-dss-page-tampering/service:${DOCKER_TAG}
    build:
      target: service
      secrets:
        - npmrc

secrets:
  npmrc:
    file: ${NPMRC_FILE}
